import { jsPDF } from 'jspdf';

export interface OrderSummaryLine {
  designCode?: string | null;
  designName?: string | null;
  fabric?: string | null;
  catalogueName?: string | null;
  quantity: number;
  basePrice?: number | null;
  remarks?: string | null;
}

export interface OrderSummaryPdfInput {
  customerName: string;
  orderNumber?: string | null;
  createdAt?: string | null;
  firmName?: string | null;
  orderLines: OrderSummaryLine[];
}

const formatMoney = (value: number) =>
  `₹${value.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;

const formatDate = (value?: string | null) => {
  if (!value) return new Date().toLocaleString('en-IN');
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? new Date().toLocaleString('en-IN') : date.toLocaleString('en-IN');
};

const safeFilePart = (value: string) =>
  value.replace(/[^a-z0-9-_]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase() || 'order';

export function downloadOrderSummaryPdf(input: OrderSummaryPdfInput) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const margin = 14;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - margin * 2;
  let y = 18;

  const addPageIfNeeded = (height = 8) => {
    if (y + height > 285) {
      doc.addPage();
      y = 18;
    }
  };

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(79, 70, 229);
  doc.text('ThreadX', margin, y);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text('Order summary', pageWidth - margin, y, { align: 'right' });
  y += 10;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text('Sales order receipt', margin, y);
  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(51, 65, 85);

  const metaRows = [
    ['Customer', input.customerName],
    ['Order no.', input.orderNumber || '—'],
    ['Date', formatDate(input.createdAt)],
    ...(input.firmName ? [['Firm', input.firmName] as [string, string]] : [])
  ];

  for (const [label, value] of metaRows) {
    addPageIfNeeded();
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, margin, y);
    doc.setFont('helvetica', 'normal');
    doc.text(String(value), margin + 28, y);
    y += 6;
  }

  y += 4;
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text('Design', margin, y);
  doc.text('Qty', margin + 98, y);
  doc.text('Rate', margin + 118, y);
  doc.text('Amount', pageWidth - margin, y, { align: 'right' });
  y += 5;
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;

  let grandTotal = 0;
  let totalQty = 0;

  for (const line of input.orderLines) {
    addPageIfNeeded(18);
    const label = line.designCode || line.designName || 'Design';
    const subtitle = [line.catalogueName, line.fabric].filter(Boolean).join(' · ');
    const rate = Number(line.basePrice) || 0;
    const amount = rate * line.quantity;
    grandTotal += amount;
    totalQty += line.quantity;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text(label, margin, y);

    doc.setFont('helvetica', 'normal');
    doc.text(String(line.quantity), margin + 98, y);
    doc.text(formatMoney(rate), margin + 118, y);
    doc.text(formatMoney(amount), pageWidth - margin, y, { align: 'right' });
    y += 5;

    if (subtitle) {
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.text(subtitle, margin, y);
      y += 4;
    }

    if (line.remarks?.trim()) {
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.text(`Remarks: ${line.remarks.trim()}`, margin, y);
      y += 4;
    }

    y += 3;
  }

  addPageIfNeeded(20);
  y += 2;
  doc.line(margin, y, pageWidth - margin, y);
  y += 7;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text(`Total quantity: ${totalQty}`, margin, y);
  doc.text(`Grand total: ${formatMoney(grandTotal)}`, pageWidth - margin, y, { align: 'right' });
  y += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  const footer = 'Generated by ThreadX. This is a computer-generated order summary.';
  const wrapped = doc.splitTextToSize(footer, contentWidth);
  doc.text(wrapped, margin, y);

  const fileToken = input.orderNumber || new Date().toISOString().slice(0, 10);
  doc.save(`threadx-order-${safeFilePart(fileToken)}.pdf`);
}
