/**
 * GENERATED FILE — do not edit by hand.
 *
 * Source: backend/constants/data/transactionTypes.tsv (Empire "TRANSACTION TYPES" export)
 * Regenerate: node backend/scripts/generateTransactionPostingRules.mjs
 *
 * One row per voucher series: its numbering series, GST document class and rates,
 * the nominal ledger it posts to, the party control account, the stock ledger it
 * moves, and the document-link chain (PREVIOUS LINK / NEXT LINK) that says which
 * document this one is raised against.
 */

export const ERP_POSTING_RULES = [
  {
    series: 'OPENING BALANCE',
    seriesCode: '00',
    billingAllowed: false,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: null,
    saleOrPurchaseAccount: 'OPENING BALANCE',
    partyAccountType: null,
    stockType: 'FINISH',
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'BANK RECEIPT',
    seriesCode: 'B1',
    billingAllowed: false,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: null,
    saleOrPurchaseAccount: null,
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'BANK PAYMENT',
    seriesCode: 'B2',
    billingAllowed: false,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: null,
    saleOrPurchaseAccount: null,
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'CASH RECEIPT',
    seriesCode: 'C1',
    billingAllowed: false,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: null,
    saleOrPurchaseAccount: 'CASH A/C',
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'CASH PAYMENT',
    seriesCode: 'C2',
    billingAllowed: false,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: null,
    saleOrPurchaseAccount: 'CASH A/C',
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'EXPENSES',
    seriesCode: 'E1',
    billingAllowed: false,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: null,
    saleOrPurchaseAccount: null,
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'JOB WORK',
    seriesCode: 'J1',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'JOBBILL',
    saleOrPurchaseAccount: 'JOB CHARGES A/C',
    partyAccountType: 'CREDITORS FOR JOB WORK',
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: 'TDS PAYABLE A/C',
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: true,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '9988',
    itcEligibility: 'Input Services',
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'JOURNAL',
    seriesCode: 'J2',
    billingAllowed: false,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: null,
    saleOrPurchaseAccount: null,
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'WORK DESP ALL',
    seriesCode: 'O',
    billingAllowed: false,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: null,
    saleOrPurchaseAccount: null,
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: false,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'SALES ORDERS',
    seriesCode: 'O1',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Sales Orders',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: null,
    partyAccountType: 'SUNDRY DEBTORS',
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: 'FINISH SALES',
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'WORK DESP LACE CHALLAN',
    seriesCode: 'O11',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Delivery Challan for job work',
    billSuffix: 'L',
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: null,
    partyAccountType: 'CREDITORS FOR EMB.JOB CHARGE',
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: 'WORK REC LACE CHALLAN',
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'WORK DESP POONAM LACE CHALLAN',
    seriesCode: 'O12',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Delivery Challan for job work',
    billSuffix: 'PL',
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: null,
    partyAccountType: 'CREDITORS FOR EMB.JOB CHARGE',
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: 'WORK REC. POONAM LACE BILLS',
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'WORK DESP.LACE SUIT CHALLAN',
    seriesCode: 'O15',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Delivery Challan for job work',
    billSuffix: 'LS',
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: null,
    partyAccountType: 'CREDITORS FOR EMB.JOB CHARGE',
    stockType: 'WORK',
    numberSeries: null,
    previousLink: null,
    nextLink: 'WORK REC. LACE SUIT BILLS',
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: -1,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'STOCK TRANSFER',
    seriesCode: 'O41',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: 'STOCKTFR',
    saleOrPurchaseAccount: null,
    partyAccountType: null,
    stockType: 'WORK',
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: 1,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'WORK DESP POONAM CHALLAN',
    seriesCode: 'O45',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Delivery Challan for job work',
    billSuffix: 'WP',
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: null,
    partyAccountType: 'CREDITORS FOR EMB.JOB CHARGE',
    stockType: 'WORK',
    numberSeries: null,
    previousLink: null,
    nextLink: 'WORK REC. POONAM BILLS',
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'WORK DESP CHALLAN',
    seriesCode: 'O5',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Delivery Challan for job work',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: null,
    partyAccountType: 'CREDITORS FOR EMB.JOB CHARGE',
    stockType: 'WORK',
    numberSeries: null,
    previousLink: null,
    nextLink: 'WORK REC. BILLS',
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: -1,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'SALES CHALLAN',
    seriesCode: 'O57',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Delivery Challan for supply on approval',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: null,
    partyAccountType: 'SUNDRY DEBTORS',
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: 'FINISH SALES (GST)',
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '5407',
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'WORK DESP.SUIT CHALLAN',
    seriesCode: 'O7',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Delivery Challan for job work',
    billSuffix: 'WS',
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: null,
    partyAccountType: 'CREDITORS FOR EMB.JOB CHARGE',
    stockType: 'WORK',
    numberSeries: null,
    previousLink: null,
    nextLink: 'WORK REC. SUIT BILLS',
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: -1,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'ADVANCE RECEIPT VOUCHER',
    seriesCode: 'OA',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Receipt Voucher',
    billSuffix: 'ADV',
    billingForm: 'BILLSDIR',
    saleOrPurchaseAccount: null,
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'ADVANCE REFUND VOUCHER',
    seriesCode: 'OF',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Refund Voucher',
    billSuffix: 'RFV',
    billingForm: 'BILLSDIR',
    saleOrPurchaseAccount: null,
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'REVERSE CHARGE SALES TO SELF',
    seriesCode: 'OR',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Invoices for inward supply from unregistered person',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: null,
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'PURCHASES (ALL)',
    seriesCode: 'P',
    billingAllowed: true,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: null,
    saleOrPurchaseAccount: null,
    partyAccountType: 'CREDITORS FOR GREY',
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'GREY PURCHASE',
    seriesCode: 'P1',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'PURBILL',
    saleOrPurchaseAccount: 'GREY PURCHASE',
    partyAccountType: 'CREDITORS FOR GREY',
    stockType: 'GREY',
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '5407',
    itcEligibility: 'Input Goods',
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: 'TCS RECEIVABLE A/C'
  },
  {
    series: 'VALUE ADDITION PURCHASE',
    seriesCode: 'P10',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'VALUE ADD.A/C',
    partyAccountType: 'CREDITORS FOR GOODS',
    stockType: 'FINISH',
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: null,
    itcEligibility: 'Input Goods',
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: 'TCS RECEIVABLE A/C'
  },
  {
    series: 'WORK REC LACE CHALLAN',
    seriesCode: 'P11',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'EMBROIDERY JOB CHARGES',
    partyAccountType: 'CREDITORS FOR EMB.JOB CHARGE',
    stockType: 'WORK',
    numberSeries: null,
    previousLink: 'WORK DESP LACE CHALLAN',
    nextLink: 'WORK REC. LACE BILLS',
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: 'TDS PAYABLE A/C',
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '9988',
    itcEligibility: 'Input Services',
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'SALARY EXP A/C',
    seriesCode: 'P12',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'SALARY A/C',
    partyAccountType: 'P & L EXPENSES',
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: 'TCS RECEIVABLE A/C'
  },
  {
    series: 'WORK REC. POONAM LACE BILLS',
    seriesCode: 'P13',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'EMBROIDERY JOB CHARGES',
    partyAccountType: 'CREDITORS FOR EMB.JOB CHARGE',
    stockType: 'WORK',
    numberSeries: null,
    previousLink: 'WORK DESP POONAM LACE CHALLAN',
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: 'TDS PAYABLE A/C',
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '9988',
    itcEligibility: 'Input Services',
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'WORK REC. LACE SUIT BILLS',
    seriesCode: 'P15',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'EMBROIDERY JOB CHARGES',
    partyAccountType: 'CREDITORS FOR EMB.JOB CHARGE',
    stockType: 'WORK',
    numberSeries: null,
    previousLink: 'WORK DESP.LACE SUIT CHALLAN',
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: 'TDS PAYABLE A/C',
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '9988',
    itcEligibility: 'Input Services',
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'FINISH PURCHASE',
    seriesCode: 'P2',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'FINISH PURCHASE',
    partyAccountType: 'CREDITORS FOR GOODS',
    stockType: 'FINISH',
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '5407',
    itcEligibility: 'Input Goods',
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: 'TCS RECEIVABLE A/C'
  },
  {
    series: 'SALES GOODS RETURN',
    seriesCode: 'P3',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Credit Note',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'SALES RETURN',
    partyAccountType: 'SUNDRY DEBTORS',
    stockType: 'FINISH',
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: true,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'WORK REC. LACE BILLS',
    seriesCode: 'P31',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'EMBROIDERY JOB CHARGES',
    partyAccountType: 'CREDITORS FOR EMB.JOB CHARGE',
    stockType: 'WORK',
    numberSeries: null,
    previousLink: 'WORK DESP LACE CHALLAN',
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: 'TDS PAYABLE A/C',
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '9988',
    itcEligibility: 'Input Services',
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'PACKING MATERIAL',
    seriesCode: 'P4',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'PACKING MATERIAL PURCHASE',
    partyAccountType: 'CREDITORS FOR PACKING MAT.',
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: 'TDS PAYABLE A/C',
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: 'Input Goods',
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'WORK REC. POONAM BILLS',
    seriesCode: 'P45',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: 'WP',
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'EMBROIDERY JOB CHARGES',
    partyAccountType: 'CREDITORS FOR EMB.JOB CHARGE',
    stockType: 'WORK',
    numberSeries: null,
    previousLink: 'WORK DESP POONAM CHALLAN',
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: 'TDS PAYABLE A/C',
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '9988',
    itcEligibility: 'Input Services',
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'WORK REC. CHALLAN',
    seriesCode: 'P5',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'EMBROIDERY JOB CHARGES',
    partyAccountType: 'CREDITORS FOR EMB.JOB CHARGE',
    stockType: 'WORK',
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: 'TDS PAYABLE A/C',
    stockEffect: 1,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '9988',
    itcEligibility: 'Input Services',
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'BOX PURCHASES',
    seriesCode: 'P6',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'PACKING MATERIAL PURCHASE',
    partyAccountType: 'CREDITORS FOR PACKING MAT.',
    stockType: 'BOX',
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: 'TCS RECEIVABLE A/C'
  },
  {
    series: 'CREDIT NOTE (TDS)',
    seriesCode: 'P66',
    billingAllowed: true,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: 'BILLSDIR',
    saleOrPurchaseAccount: 'TDS RECEIVABLE A/C (194Q)',
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C PURCHASE',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'WORK REC. BILLS',
    seriesCode: 'P7',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'EMBROIDERY JOB CHARGES',
    partyAccountType: 'CREDITORS FOR EMB.JOB CHARGE',
    stockType: 'WORK',
    numberSeries: null,
    previousLink: 'WORK DESP CHALLAN',
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: 'TDS PAYABLE A/C',
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '9988',
    itcEligibility: 'Input Services',
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'CREDIT NOTE (TCS)',
    seriesCode: 'P77',
    billingAllowed: true,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: 'BILLSDIR',
    saleOrPurchaseAccount: 'TCS RECEIVABLE A/C',
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C PURCHASE',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'GENERAL PURCHASES',
    seriesCode: 'P8',
    billingAllowed: true,
    singleRef: false,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'BILLSDIR',
    saleOrPurchaseAccount: 'PRINTING & STATIONERY A/C',
    partyAccountType: 'CREDITORS FOR PACKING MAT.',
    stockType: 'WORK',
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: 1,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: null,
    itcEligibility: 'Input Goods',
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: 'TCS RECEIVABLE A/C'
  },
  {
    series: 'WORK REC. SUIT BILLS',
    seriesCode: 'P9',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'EMBROIDERY JOB CHARGES',
    partyAccountType: 'CREDITORS FOR EMB.JOB CHARGE',
    stockType: 'WORK',
    numberSeries: null,
    previousLink: 'WORK DESP CHALLAN',
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: 'TDS PAYABLE A/C',
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '9988',
    itcEligibility: 'Input Services',
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'CREDIT NOTE (ON SALES)',
    seriesCode: 'P91',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Credit Note',
    billSuffix: 'C',
    billingForm: 'BILLSDIR',
    saleOrPurchaseAccount: 'DISCOUNT A/C SALES',
    partyAccountType: 'SUNDRY DEBTORS',
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C SALES',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'CREDIT NOTE (ON PURCHASES)',
    seriesCode: 'P92',
    billingAllowed: true,
    singleRef: false,
    gstDocumentType: 'Credit Note (inward)',
    billSuffix: null,
    billingForm: 'BILLSDIR',
    saleOrPurchaseAccount: 'DISCOUNT A/C PURCHASE',
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C PURCHASE',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: null,
    itcEligibility: 'Input Goods',
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: 'TCS RECEIVABLE A/C'
  },
  {
    series: 'PURCHASE (GST INPUT SERVICES)',
    seriesCode: 'P93',
    billingAllowed: true,
    singleRef: false,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'PURCHASE (SERVICES)',
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C PURCHASE',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: 'TDS PAYABLE A/C',
    stockEffect: 1,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: 'Input Services',
    cgstPercent: 9,
    sgstPercent: 9,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'PURCHASE (GST CAPITAL GOODS)',
    seriesCode: 'P94',
    billingAllowed: true,
    singleRef: false,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'PURCHASE (CAPTIAL GOODS/ASSETS)',
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C PURCHASE',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: 'TDS PAYABLE A/C',
    stockEffect: 1,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: 'Capital Goods',
    cgstPercent: 9,
    sgstPercent: 9,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'PURCHASE (GST GENERAL GOODS)',
    seriesCode: 'P95',
    billingAllowed: true,
    singleRef: false,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'PURCHASE (GENERAL GOODS)',
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C PURCHASE',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: 'TDS PAYABLE A/C',
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: 'Input Goods',
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'SALES',
    seriesCode: 'S',
    billingAllowed: true,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: null,
    saleOrPurchaseAccount: null,
    partyAccountType: 'SUNDRY DEBTORS',
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'FINISH SALES',
    seriesCode: 'S1',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Invoices for outward supply',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'SALES A/C',
    partyAccountType: 'SUNDRY DEBTORS',
    stockType: 'FINISH',
    numberSeries: null,
    previousLink: 'SALES ORDERS',
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: -1,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '5407',
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: 'TCS PAYABLE A/C'
  },
  {
    series: 'GREY PURCHASE RETURN',
    seriesCode: 'S2',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Debit Note (inward)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'GREY PURCHASE RETURN A/C',
    partyAccountType: null,
    stockType: 'GREY',
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: 'TCS RECEIVABLE A/C'
  },
  {
    series: 'FINISH PURCHASE RETURN',
    seriesCode: 'S3',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Debit Note (inward)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'FINISH PURCHASE RETURN A/C',
    partyAccountType: null,
    stockType: 'FINISH',
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: 'TCS RECEIVABLE A/C'
  },
  {
    series: 'CASH SALES',
    seriesCode: 'S4',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Invoices for outward supply',
    billSuffix: 'C',
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'CASH SALES A/C',
    partyAccountType: null,
    stockType: 'FINISH',
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '5407',
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: 'TCS PAYABLE A/C'
  },
  {
    series: 'GREY SALES',
    seriesCode: 'S5',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Invoices for outward supply',
    billSuffix: 'G',
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'GREY SALES A/C',
    partyAccountType: null,
    stockType: 'GREY',
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '5407',
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: 'TCS PAYABLE A/C'
  },
  {
    series: 'FINISH SALES (GST)',
    seriesCode: 'S51',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Invoices for outward supply',
    billSuffix: 'F',
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'SALES A/C',
    partyAccountType: 'SUNDRY DEBTORS',
    stockType: 'FINISH',
    numberSeries: null,
    previousLink: 'SALES CHALLAN',
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: -1,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: true,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '5407',
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: 'TCS PAYABLE A/C'
  },
  {
    series: 'FENT SALES',
    seriesCode: 'S6',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Invoices for outward supply',
    billSuffix: 'W',
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: 'FENT SALES A/C',
    partyAccountType: 'SUNDRY DEBTORS',
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '5407',
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: 'TCS PAYABLE A/C'
  },
  {
    series: 'DEBIT NOTE (TDS)',
    seriesCode: 'S66',
    billingAllowed: true,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: 'TDS',
    billingForm: 'BILLSDIR',
    saleOrPurchaseAccount: 'TDS PAYABLE A/C (194Q)',
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C SALES',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'DEBIT NOTE (TCS)',
    seriesCode: 'S77',
    billingAllowed: true,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: 'TCS',
    billingForm: 'BILLSDIR',
    saleOrPurchaseAccount: 'TCS PAYABLE A/C',
    partyAccountType: 'SUNDRY DEBTORS',
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C SALES',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'DEBIT NOTE (ON SALES)',
    seriesCode: 'S91',
    billingAllowed: true,
    singleRef: false,
    gstDocumentType: 'Debit Note',
    billSuffix: 'D',
    billingForm: 'BILLSDIR',
    saleOrPurchaseAccount: 'DISCOUNT A/C SALES',
    partyAccountType: 'SUNDRY DEBTORS',
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C SALES',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: '5407',
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: 'TCS PAYABLE A/C'
  },
  {
    series: 'DEBIT NOTE (ON PURCHASES)',
    seriesCode: 'S92',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Debit Note (inward)',
    billSuffix: null,
    billingForm: 'BILLSDIR',
    saleOrPurchaseAccount: 'DISCOUNT A/C PURCHASE',
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: true,
    zeroGraceForInterest: false,
    discountAccount: 'DISCOUNT A/C PURCHASE',
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: true,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: 'TCS RECEIVABLE A/C'
  },
  {
    series: 'TDS',
    seriesCode: 'T1',
    billingAllowed: true,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: 'JOBBILL',
    saleOrPurchaseAccount: null,
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'VATAV',
    seriesCode: 'V1',
    billingAllowed: false,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: null,
    saleOrPurchaseAccount: null,
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'CLOSING ENTRIES (TRADING)',
    seriesCode: 'V2',
    billingAllowed: false,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: null,
    saleOrPurchaseAccount: null,
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'CLOSING ENTRIES (P & L)',
    seriesCode: 'V3',
    billingAllowed: false,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: null,
    saleOrPurchaseAccount: null,
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'VAT JV',
    seriesCode: 'V4',
    billingAllowed: false,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: null,
    saleOrPurchaseAccount: null,
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'COMMISSION JVS',
    seriesCode: 'V5',
    billingAllowed: false,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: null,
    saleOrPurchaseAccount: null,
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'UNADJ PAYMENT',
    seriesCode: 'XX',
    billingAllowed: true,
    singleRef: false,
    gstDocumentType: null,
    billSuffix: null,
    billingForm: null,
    saleOrPurchaseAccount: null,
    partyAccountType: null,
    stockType: null,
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: null,
    itcEligibility: null,
    cgstPercent: 0,
    sgstPercent: 0,
    gstAccount: null,
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  },
  {
    series: 'MILL REC.CHALLAN',
    seriesCode: 'O3',
    billingAllowed: true,
    singleRef: true,
    gstDocumentType: 'Inward Invoices (All Purchases)',
    billSuffix: null,
    billingForm: 'CHALLAN',
    saleOrPurchaseAccount: null,
    partyAccountType: 'CREDITORS FOR DYEING JOB CHARG',
    stockType: 'GREY',
    numberSeries: null,
    previousLink: null,
    nextLink: null,
    discountJvs: false,
    zeroGraceForInterest: false,
    discountAccount: null,
    designNosEntry: false,
    tdsPercent: 0,
    tdsAccount: null,
    stockEffect: null,
    compulsoryLink: false,
    showAllEntriesInPick: false,
    allCompaniesDataInPick: false,
    copyItemDetailsAfterRef: false,
    warnOnManualEntry: true,
    singleGstRateForBill: false,
    defaultHsnCode: '9988',
    itcEligibility: 'Input Services',
    cgstPercent: 2.5,
    sgstPercent: 2.5,
    gstAccount: 'GST PAYABLE A/C',
    oldVatAccount: null,
    stageGroup: null,
    mainStageLink: null,
    finalStageOfJobCard: false,
    includeCostingOfStage: false,
    scanPath: null,
    tcsAccount: null
  }
];

const RULE_BY_SERIES = new Map(
  ERP_POSTING_RULES.map(row => [row.series.toUpperCase(), row])
);

export function getPostingRule(transactionType) {
  const upper = String(transactionType || '').trim().toUpperCase();
  if (!upper) return undefined;
  return RULE_BY_SERIES.get(upper);
}

/** Party control account for this series, or the caller's fallback when the master is blank. */
export function postingPartyAccountType(
  transactionType,
  fallback = null
) {
  return getPostingRule(transactionType)?.partyAccountType || fallback;
}

/** Nominal Sale/Pur ledger for this series. */
export function postingSaleOrPurchaseAccount(transactionType) {
  return getPostingRule(transactionType)?.saleOrPurchaseAccount || null;
}

export function getGstDocumentType(transactionType) {
  return getPostingRule(transactionType)?.gstDocumentType || null;
}

export function getStockType(transactionType) {
  return getPostingRule(transactionType)?.stockType || null;
}

/** +1 brings stock in, -1 sends it out, null leaves stock untouched. */
export function getStockEffect(transactionType) {
  const found = getPostingRule(transactionType);
  return found && found.stockEffect != null ? found.stockEffect : null;
}

/** True when the series belongs to the billing system rather than general entries. */
export function isBillingSeries(transactionType) {
  return getPostingRule(transactionType)?.billingAllowed === true;
}

/** True when the document carries a single party ledger. */
export function requiresSingleReference(transactionType) {
  return getPostingRule(transactionType)?.singleRef === true;
}

/** PREVIOUS LINK — the series this document is raised against. */
export function getPreviousLink(transactionType) {
  return getPostingRule(transactionType)?.previousLink || null;
}

/** NEXT LINK — the series that consumes this document. */
export function getNextLink(transactionType) {
  return getPostingRule(transactionType)?.nextLink || null;
}

/**
 * Every series that can feed `transactionType`.
 *
 * The master states links from both ends and is not always symmetric: WORK REC.
 * SUIT BILLS names WORK DESP CHALLAN as its previous link, while WORK DESP.SUIT
 * CHALLAN names WORK REC. SUIT BILLS as its next link. Taking the union of both
 * directions honours every link the master declares.
 */
export function getSourceSeriesFor(transactionType) {
  const upper = String(transactionType || '').trim().toUpperCase();
  if (!upper) return [];
  const sources = new Set();
  const own = getPostingRule(upper)?.previousLink;
  if (own) sources.add(own);
  for (const row of ERP_POSTING_RULES) {
    if (row.nextLink && row.nextLink.toUpperCase() === upper) sources.add(row.series);
  }
  return Array.from(sources);
}

/** Every series that can consume `transactionType`, i.e. the reverse of the above. */
export function getTargetSeriesFor(transactionType) {
  const upper = String(transactionType || '').trim().toUpperCase();
  if (!upper) return [];
  const targets = new Set();
  const own = getPostingRule(upper)?.nextLink;
  if (own) targets.add(own);
  for (const row of ERP_POSTING_RULES) {
    if (row.previousLink && row.previousLink.toUpperCase() === upper) targets.add(row.series);
  }
  return Array.from(targets);
}

/** True when the series may only be raised by picking one of its source documents. */
export function requiresCompulsoryLink(transactionType) {
  return getPostingRule(transactionType)?.compulsoryLink === true;
}

/** True when picking a source document should also copy its item lines across. */
export function copiesItemDetailsFromSource(transactionType) {
  return getPostingRule(transactionType)?.copyItemDetailsAfterRef === true;
}

/** True when the picker should list fully-consumed source documents as well. */
export function showsAllEntriesInPick(transactionType) {
  return getPostingRule(transactionType)?.showAllEntriesInPick === true;
}

/** True when typing this document's number by hand should raise a warning. */
export function warnsOnManualEntry(transactionType) {
  return getPostingRule(transactionType)?.warnOnManualEntry === true;
}

/** Default GST rate for the series: CGST% + SGST% from the master. */
export function postingGstRate(transactionType) {
  const found = getPostingRule(transactionType);
  if (!found) return null;
  const total = (Number(found.cgstPercent) || 0) + (Number(found.sgstPercent) || 0);
  return total > 0 ? total : null;
}

const GSTR1_DOCUMENTS = new Set([
  'Invoices for outward supply',
  'Credit Note',
  'Debit Note'
]);

const GSTR2_DOCUMENTS = new Set([
  'Inward Invoices (All Purchases)',
  'Invoices for inward supply from unregistered person',
  'Credit Note (inward)',
  'Debit Note (inward)'
]);

export function gstReturnSection(transactionType) {
  const doc = getGstDocumentType(transactionType);
  if (!doc) return 'NONE';
  if (GSTR1_DOCUMENTS.has(doc)) return 'GSTR-1';
  if (GSTR2_DOCUMENTS.has(doc)) return 'GSTR-2';
  return 'NONE';
}

/** Delivery challans move goods without creating a tax liability. */
export function isDeliveryChallanDocument(transactionType) {
  const doc = getGstDocumentType(transactionType);
  return Boolean(doc && doc.startsWith('Delivery Challan'));
}

/**
 * Document number as printed: series code, optional GST suffix, padded counter.
 * The stored counter is untouched — this is display formatting only.
 */
export function formatSeriesBillNumber(
  transactionType,
  counter,
  pad = 4
) {
  if (counter == null || counter === '') return '';
  const numeric = Number(counter);
  const body = Number.isFinite(numeric) && numeric > 0
    ? String(Math.trunc(numeric)).padStart(pad, '0')
    : String(counter);
  const found = getPostingRule(transactionType);
  if (!found) return body;
  return [found.seriesCode, found.billSuffix, body].filter(Boolean).join('/');
}

/** One-line "where does this entry land" summary for entry screens. */
export function postingSummary(transactionType) {
  const found = getPostingRule(transactionType);
  if (!found) return '—';
  const parts = [
    found.saleOrPurchaseAccount,
    found.partyAccountType,
    found.stockType ? `Stock: ${found.stockType}` : null
  ].filter(Boolean);
  return parts.length ? parts.join(' · ') : '—';
}

/** Distinct Sale/Pur A/C names from the master, for pickers. */
export const ERP_SALE_PURCHASE_ACCOUNTS = Array.from(
  new Set(ERP_POSTING_RULES.map(row => row.saleOrPurchaseAccount).filter(Boolean))
).sort((a, b) => String(a).localeCompare(String(b)));

