-- Work receipt billing: deductions + GST / add-less / TDS fields
ALTER TABLE "WorkReceipt" ADD COLUMN "totalFresh" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "WorkReceipt" ADD COLUMN "grossAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "WorkReceipt" ADD COLUMN "discountPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "WorkReceipt" ADD COLUMN "discountAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "WorkReceipt" ADD COLUMN "otherLess" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "WorkReceipt" ADD COLUMN "otherAdd" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "WorkReceipt" ADD COLUMN "tdsOnAmt" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "WorkReceipt" ADD COLUMN "tdsPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "WorkReceipt" ADD COLUMN "tdsAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "WorkReceipt" ADD COLUMN "netAfterTds" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "WorkReceipt" ALTER COLUMN "hsnCode" SET DEFAULT '9988';
