-- AlterTable
ALTER TABLE "BankEntry" ADD COLUMN "companyName" TEXT;
ALTER TABLE "BankEntry" ADD COLUMN "chequeNumber" TEXT;
ALTER TABLE "BankEntry" ADD COLUMN "chequeDate" TIMESTAMP(3);
ALTER TABLE "BankEntry" ADD COLUMN "slipNumber" TEXT;
ALTER TABLE "BankEntry" ADD COLUMN "billNumber" TEXT;
ALTER TABLE "BankEntry" ADD COLUMN "billAllocations" JSONB;
ALTER TABLE "BankEntry" ADD COLUMN "grossAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "BankEntry" ADD COLUMN "adjustPending" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "BankEntry" ADD COLUMN "netBillAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "BankEntry" ADD COLUMN "adjustAdd" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "BankEntry" ADD COLUMN "taxableValuePaidBills" DOUBLE PRECISION NOT NULL DEFAULT 0;
